[package]
name = "ast"
version = "0.1.0"
authors = ["yangdao <458424869@qq.com>"]
edition = "2018"


[dependencies]
serde_json = "1.0.57"
serde_derive = "1.0.115"
serde_cbor = "0.11.1"
serde = { version = "1.0", features = ["derive"] }